UTILSDIR := utils/args

$(OBJDIR)/httpc_args.o: $(UTILSDIR)/httpc_args.cc
	$(CC) $(CFLAGS) -c -o $@ $<

$(OBJDIR)/httpc_options.o: $(UTILSDIR)/httpc_options.cc
	$(CC) $(CFLAGS) -c -o $@ $<

$(OBJDIR)/httpc_option_error.o: $(UTILSDIR)/httpc_option_error.cc
	$(CC) $(CFLAGS) -c -o $@ $<



