COREDIR := core

$(OBJDIR)/httpc_proxy.o: $(COREDIR)/httpc_proxy.cc
	$(CC) $(CFLAGS) -c -o $@ $<

$(OBJDIR)/httpc_handler.o: $(COREDIR)/httpc_handler.cc
	$(CC) $(CFLAGS) -c -o $@ $<

$(OBJDIR)/httpc_http_response.o: $(COREDIR)/httpc_http_response.cc
	$(CC) $(CFLAGS) -c -o $@ $<

$(OBJDIR)/httpc_http_request.o: $(COREDIR)/httpc_http_request.cc
	$(CC) $(CFLAGS) -c -o $@ $<




